import assert from "node:assert/strict";
import fs from "node:fs/promises";

import {
  DocumentModel,
  helpArtifact,
  HELP_CATALOG,
  PdfArtifact,
  Presentation,
  Workbook,
} from "open-office-artifact-tool";

assert.ok(HELP_CATALOG.length >= 40);
assert.equal(HELP_CATALOG.length, 161);
assert.ok(HELP_CATALOG.every((item) => item.schema?.parameters && item.schema?.returns));
assert.ok(HELP_CATALOG.some((item) => item.name === "Workbook.create"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.worksheets.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.recalculate"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.resolve"));
assert.ok(HELP_CATALOG.some((item) => item.name === "SpreadsheetFile.inspectXlsx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "SpreadsheetFile.patchXlsx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.compose"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.addNotes"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.comments.addThread"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.connectors.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.theme"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.layouts.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.applyLayout"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.addHyperlink"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.applyDesignPreset"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.layoutJson"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.resolve"));
assert.ok(HELP_CATALOG.some((item) => item.name === "DocumentFile.importDocx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.extractTables"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.addPage"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.addTable"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createPdfjsParser"));
assert.ok(HELP_CATALOG.some((item) => item.name === "verifyArtifact"));
assert.ok(HELP_CATALOG.some((item) => item.name === "visualQaArtifact"));
assert.ok(HELP_CATALOG.some((item) => item.name === "renderArtifact"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.format"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.formulaGraph"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.AVERAGE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.XLOOKUP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TEXTJOIN"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.SUMPRODUCT"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.HLOOKUP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.IFERROR"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISNUMBER"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISTEXT"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISBLANK"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISERROR"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.AVERAGEIF"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.AVERAGEIFS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.NOT"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TAKE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.DROP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.CHOOSECOLS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.CHOOSEROWS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TOCOL"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TOROW"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.WRAPROWS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.WRAPCOLS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createPlaywrightRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createSharpRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createPopplerRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createLibreOfficeRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.inspectPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.exportPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.importPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.patchPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.slides.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PdfFile.inspectPdf"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createNativeOfficeRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "renderFileWithNativeOffice"));
assert.ok(HELP_CATALOG.find((item) => item.name === "workbook.inspect")?.options?.includes("include/fields"));
assert.ok(HELP_CATALOG.find((item) => item.name === "workbook.inspect")?.schema?.parameters?.kind);
assert.ok(HELP_CATALOG.find((item) => item.name === "renderArtifact")?.schema?.returns?.blob);
assert.ok(HELP_CATALOG.find((item) => item.name === "range.conditionalFormats.add")?.schema?.parameters?.colors);
assert.ok(HELP_CATALOG.find((item) => item.name === "DocumentFile.patchDocx")?.schema?.parameters?.patches);
assert.ok(HELP_CATALOG.find((item) => item.name === "PdfFile.importPdf")?.schema?.returns?.pdf);
assert.ok(HELP_CATALOG.find((item) => item.name === "renderArtifact")?.returns?.includes("FileBlob"));
assert.ok(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.examples?.some((example) => example.includes("pixelDiff")));
const formulaCatalog = HELP_CATALOG.filter((item) => item.name.startsWith("fx."));
assert.equal(formulaCatalog.length, 54);
assert.ok(formulaCatalog.every((item) => item.schema?.parameters?.formula?.required));
assert.ok(formulaCatalog.every((item) => item.schema?.parameters?.arguments?.type === "unknown[]"));
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.AND")?.schema?.returns?.value?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.FILTER")?.schema?.returns?.value?.type, "unknown[][]");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.TEXTJOIN")?.schema?.returns?.value?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.LEN")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.XLOOKUP")?.schema?.returns?.value?.type, "unknown");
const sharedCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "shared");
assert.equal(sharedCatalog.length, 10);
assert.ok(sharedCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "createPopplerRenderer")?.schema?.parameters?.dpi?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "createNativeOfficeRenderer")?.schema?.parameters?.args?.type, "string[]");
assert.equal(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.schema?.parameters?.pixelDiff?.type, "boolean|object");
const pdfCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "pdf");
assert.equal(pdfCatalog.length, 17);
assert.ok(pdfCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.addText")?.schema?.parameters?.bbox?.type, "number[]");
assert.equal(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.returns?.blob?.type, "FileBlob");
const documentCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "document");
assert.equal(documentCatalog.length, 27);
assert.ok(documentCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addSection")?.schema?.parameters?.margins?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "DocumentFile.importDocx")?.schema?.returns?.document?.type, "DocumentModel");
const presentationCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "presentation");
assert.equal(presentationCatalog.length, 26);
assert.ok(presentationCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "slide.charts.add")?.schema?.parameters?.series?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.importPptx")?.schema?.returns?.presentation?.type, "Presentation");
const workbookCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "workbook");
assert.equal(workbookCatalog.length, 81);
assert.ok(workbookCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "workbook.trace")?.schema?.parameters?.reference?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.exportXlsx")?.schema?.returns?.blob?.type, "FileBlob");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.inspectXlsx")?.schema?.parameters?.maxTotalBytes?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.patches?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.syncContentTypes?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.relationship?.type, "object");

const workbook = Workbook.create();
const presentation = Presentation.create();
const document = DocumentModel.create({ paragraphs: ["Doc"] });
const pdf = PdfArtifact.create({ text: "PDF" });

assert.match(workbook.help("sheet.charts.add").ndjson, /worksheet chart/);
assert.match(workbook.help("workbook.formulaGraph").ndjson, /dependency graph/);
assert.match(workbook.help("fx.AVERAGE").ndjson, /Average numeric values/);
assert.match(workbook.help("fx.XLOOKUP").ndjson, /lookup/);
assert.match(workbook.help("fx.TEXTJOIN").ndjson, /delimiter/);
assert.match(workbook.help("fx.SUMPRODUCT").ndjson, /products/);
assert.match(workbook.help("fx.HLOOKUP").ndjson, /first row/);
assert.match(workbook.help("fx.IFERROR").ndjson, /formula error/);
assert.match(workbook.help("fx.AVERAGEIFS").ndjson, /criteria ranges/);
assert.match(presentation.help("slide.compose").ndjson, /compose tree/);
assert.match(presentation.help("slide.addNotes").ndjson, /speaker notes/);
assert.match(presentation.help("slide.connectors.add").ndjson, /connector line/);
assert.match(presentation.help("presentation.theme").ndjson, /theme colors/);
assert.match(presentation.help("presentation.layouts.add").ndjson, /slide layout/);
assert.match(document.help("document.addField").ndjson, /fldSimple/);
assert.match(document.help("document.applyDesignPreset").ndjson, /design preset/);
assert.match(document.help("document.layoutJson").ndjson, /layout JSON/);
assert.match(document.help("document.resolve").ndjson, /stable document/);
assert.match(document.help("DocumentFile.importDocx").ndjson, /Import DOCX bytes/);
assert.match(pdf.help("extractTables").ndjson, /table values/);
assert.match(pdf.help("createPdfjsParser").ndjson, /positioned text/);
assert.match(helpArtifact("*", "renderArtifact").ndjson, /FileBlob metadata/);
assert.match(helpArtifact("shared", "visualQaArtifact").ndjson, /baseline render/);
assert.match(helpArtifact("shared", "createPlaywrightRenderer").ndjson, /Playwright renderer adapter/);
assert.match(helpArtifact("shared", "createSharpRenderer").ndjson, /sharp renderer adapter/);
assert.match(helpArtifact("shared", "createPopplerRenderer").ndjson, /Poppler CLI renderer adapter/);
assert.match(helpArtifact("shared", "createLibreOfficeRenderer").ndjson, /LibreOffice CLI renderer adapter/);
assert.match(helpArtifact("presentation", "PresentationFile.inspectPptx").ndjson, /PPTX package/);
assert.match(helpArtifact("pdf", "PdfFile.inspectPdf").ndjson, /PDF bytes/);
assert.match(helpArtifact("shared", "createNativeOfficeRenderer").ndjson, /native Office renderer adapter/);
assert.match(helpArtifact("shared", "renderFileWithNativeOffice").ndjson, /native Office bridge command/);
assert.match(helpArtifact("shared", "pixelDiff").ndjson, /visualQaArtifact/);
assert.match(helpArtifact("workbook", "include\/fields").ndjson, /workbook.inspect/);
assert.match(helpArtifact("workbook", "colorScale").ndjson, /range\.conditionalFormats\.add/);
assert.match(helpArtifact("document", "maxPatchBytes").ndjson, /DocumentFile\.patchDocx/);
assert.match(helpArtifact(workbook, "fx.PMT").ndjson, /financial/);
assert.equal(helpArtifact("presentation", "sheet.charts.add").ndjson, "");
const apiDocs = await fs.readFile(new URL("../docs/api.md", import.meta.url), "utf8");
assert.match(apiDocs, /### shared details/);
assert.match(apiDocs, /#### `renderArtifact`/);
assert.match(apiDocs, /await renderArtifact\(document/);
assert.match(apiDocs, /#### `workbook.inspect`/);
assert.match(apiDocs, /include\/fields/);
assert.match(apiDocs, /\*\*Schema parameters:\*\*/);
assert.match(apiDocs, /`kind` \(string\)/);
assert.match(apiDocs, /`blob` \(FileBlob\)/);
assert.match(apiDocs, /DocumentFile\.patchDocx/);
assert.match(apiDocs, /#### `fx\.FILTER`/);
assert.match(apiDocs, /Spilled two-dimensional formula result/);
assert.match(apiDocs, /#### `createPopplerRenderer`/);
assert.match(apiDocs, /`dpi` \(number\)/);
assert.match(apiDocs, /#### `visualQaArtifact`/);
assert.match(apiDocs, /#### `pdf\.addPage`/);
assert.match(apiDocs, /#### `pdf\.addTable`/);
assert.match(apiDocs, /#### `document\.resolve`/);
assert.match(apiDocs, /#### `DocumentFile\.importDocx`/);
assert.match(apiDocs, /#### `presentation\.slides\.add`/);
assert.match(apiDocs, /#### `PresentationFile\.importPptx`/);
assert.match(apiDocs, /#### `workbook\.worksheets\.add`/);
assert.match(apiDocs, /#### `workbook\.recalculate`/);
assert.match(apiDocs, /#### `fx\.TAKE`/);
assert.match(apiDocs, /#### `SpreadsheetFile\.inspectXlsx`/);
assert.match(apiDocs, /#### `PresentationFile\.patchPptx`/);

console.log("help smoke ok");
