import assert from "node:assert/strict";
import fs from "node:fs/promises";

import {
  DocumentModel,
  helpArtifact,
  HELP_CATALOG,
  PdfArtifact,
  Presentation,
  Workbook,
} from "open-office-artifact-tool";

assert.ok(HELP_CATALOG.length >= 40);
assert.equal(HELP_CATALOG.length, 235);
assert.ok(HELP_CATALOG.every((item) => item.schema?.parameters && item.schema?.returns));
assert.ok(HELP_CATALOG.some((item) => item.name === "Workbook.create"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.setDateSystem"));
assert.ok(HELP_CATALOG.some((item) => item.name === "worksheet.freezePanes.freezeRows"));
assert.ok(HELP_CATALOG.some((item) => item.name === "worksheet.freezePanes.freezeColumns"));
assert.ok(HELP_CATALOG.some((item) => item.name === "worksheet.freezePanes.unfreeze"));
assert.ok(HELP_CATALOG.some((item) => item.name === "worksheet.mergeCells"));
assert.ok(HELP_CATALOG.some((item) => item.name === "worksheet.unmergeCells"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.merge"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.unmerge"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.fillDown"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.fillRight"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.format.autofitColumns"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.format.autofitRows"));
assert.match(HELP_CATALOG.find((item) => item.name === "workbook.structuredReferences")?.summary || "", /#This Row/);
assert.match(HELP_CATALOG.find((item) => item.name === "workbook.structuredReferences")?.summary || "", /space intersections/);
assert.match(HELP_CATALOG.find((item) => item.name === "fx.COUNTIF")?.summary || "", /wildcard/);
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.worksheets.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.recalculate"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.resolve"));
assert.ok(HELP_CATALOG.some((item) => item.name === "SpreadsheetFile.inspectXlsx"));
assert.match(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.importXlsx")?.schema?.returns?.workbook?.description || "", /drawing/i);
assert.ok(HELP_CATALOG.some((item) => item.name === "SpreadsheetFile.patchXlsx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.masters.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.masters.getItem"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.master.setTheme"));
assert.match(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.patchXlsx")?.summary || "", /drawing\/image\/chart\/pivot source references/);
assert.match(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.patchXlsx")?.schema?.parameters?.sourceReference?.description || "", /pivotCacheDefinition requires a unique cacheId/);
assert.match(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.importXlsx")?.schema?.returns?.workbook?.description || "", /pivots\/caches/);
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.MEDIAN"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.MODE.SNGL"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.RANK.EQ"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ROUNDUP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.compose"));
assert.match(HELP_CATALOG.find((item) => item.name === "shape.text.set")?.summary || "", /relative action, or custom-show hyperlinks/);
assert.match(HELP_CATALOG.find((item) => item.name === "shape.text.set")?.schema?.parameters?.text?.description || "", /nextSlide.*previousSlide.*firstSlide.*lastSlide.*endShow/);
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.groups.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.addNotes"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.comments.addThread"));
assert.match(HELP_CATALOG.find((item) => item.name === "slide.comments.addThread")?.summary || "", /commentAuthors\.xml.*Office 2021.*drawing\/group paths.*nested shape text-range monikers/);
assert.match(HELP_CATALOG.find((item) => item.name === "slide.comments.addThread")?.schema?.parameters?.target?.description || "", /nested shapeId\/text ranges/);
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.connectors.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.theme"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.master"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.layouts.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "slide.applyLayout"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.addHyperlink"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.addBibliographySource"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.replyToComment"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.applyDesignPreset"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.setSettings"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.setSectionSettings"));
assert.match(HELP_CATALOG.find((item) => item.name === "DocumentFile.patchDocx")?.schema?.parameters?.sourceReference?.description || "", /documentProtection/);
assert.ok(HELP_CATALOG.some((item) => item.name === "document.layoutJson"));
assert.ok(HELP_CATALOG.some((item) => item.name === "document.resolve"));
assert.ok(HELP_CATALOG.some((item) => item.name === "DocumentFile.importDocx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.extractTables"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.addPage"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.page.setReadingOrder"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.addTable"));
assert.ok(HELP_CATALOG.some((item) => item.name === "pdf.addFlowText"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createPdfjsParser"));
assert.ok(HELP_CATALOG.some((item) => item.name === "verifyArtifact"));
assert.ok(HELP_CATALOG.some((item) => item.name === "visualQaArtifact"));
assert.ok(HELP_CATALOG.some((item) => item.name === "renderArtifact"));
assert.ok(HELP_CATALOG.some((item) => item.name === "range.format"));
assert.ok(HELP_CATALOG.some((item) => item.name === "workbook.formulaGraph"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.AVERAGE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.XLOOKUP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.XMATCH"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TEXTJOIN"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.SUMPRODUCT"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.HLOOKUP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.IFERROR"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISNUMBER"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISTEXT"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISBLANK"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISERROR"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.IFNA"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISNA"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.ISERR"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.NA"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.NETWORKDAYS.INTL"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.WORKDAY.INTL"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.DATEVALUE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TIME"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TIMEVALUE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.HOUR"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.MINUTE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.SECOND"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.VALUE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.AVERAGEIF"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.AVERAGEIFS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.NOT"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TAKE"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.DROP"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.CHOOSECOLS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.CHOOSEROWS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TOCOL"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.TOROW"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.WRAPROWS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.WRAPCOLS"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.HSTACK"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.VSTACK"));
assert.ok(HELP_CATALOG.some((item) => item.name === "fx.EXPAND"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createPlaywrightRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createSharpRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createPopplerRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createLibreOfficeRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.inspectPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.exportPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.importPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "PresentationFile.patchPptx"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.slides.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.customShows.add"));
assert.ok(HELP_CATALOG.some((item) => item.name === "presentation.customShows.getItem"));
assert.match(HELP_CATALOG.find((item) => item.name === "shape.text.set")?.schema?.parameters?.text?.description || "", /customShow.*returnToSlide/);
assert.ok(HELP_CATALOG.some((item) => item.name === "PdfFile.inspectPdf"));
assert.ok(HELP_CATALOG.some((item) => item.name === "createNativeOfficeRenderer"));
assert.ok(HELP_CATALOG.some((item) => item.name === "renderFileWithNativeOffice"));
assert.ok(HELP_CATALOG.find((item) => item.name === "workbook.inspect")?.options?.includes("include/fields"));
assert.ok(HELP_CATALOG.find((item) => item.name === "workbook.inspect")?.schema?.parameters?.kind);
assert.ok(HELP_CATALOG.find((item) => item.name === "renderArtifact")?.schema?.returns?.blob);
assert.ok(HELP_CATALOG.find((item) => item.name === "range.conditionalFormats.add")?.schema?.parameters?.colors);
assert.equal(HELP_CATALOG.find((item) => item.name === "range.format")?.schema?.parameters?.columnWidthPx?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "range.format")?.schema?.parameters?.rowHidden?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "range.format")?.schema?.parameters?.protection?.type, "object");
assert.match(HELP_CATALOG.find((item) => item.name === "range.format")?.schema?.parameters?.alignment?.description || "", /textRotation/);
assert.match(HELP_CATALOG.find((item) => item.name === "range.format")?.schema?.parameters?.border?.description || "", /per-edge/);
assert.ok(HELP_CATALOG.find((item) => item.name === "DocumentFile.patchDocx")?.schema?.parameters?.patches);
assert.equal(HELP_CATALOG.find((item) => item.name === "DocumentFile.importDocx")?.schema?.parameters?.preferNative?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addHeader")?.schema?.parameters?.referenceType?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addFooter")?.schema?.parameters?.referenceType?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addHeader")?.schema?.parameters?.activateVariant?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addFooter")?.schema?.parameters?.activateVariant?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.setSectionSettings")?.schema?.parameters?.differentFirstPage?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addBookmark")?.schema?.parameters?.endTarget?.type, "string|object");
assert.match(HELP_CATALOG.find((item) => item.name === "document.addBookmark")?.schema?.parameters?.target?.description || "", /table\.getCell/);
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addBibliographySource")?.schema?.parameters?.tag?.required, true);
assert.ok(HELP_CATALOG.find((item) => item.name === "PdfFile.importPdf")?.schema?.returns?.pdf);
assert.ok(HELP_CATALOG.find((item) => item.name === "renderArtifact")?.returns?.includes("FileBlob"));
assert.ok(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.examples?.some((example) => example.includes("pixelDiff")));
const formulaCatalog = HELP_CATALOG.filter((item) => item.name.startsWith("fx."));
assert.equal(formulaCatalog.length, 88);
assert.ok(formulaCatalog.every((item) => item.schema?.parameters?.formula?.required));
assert.ok(formulaCatalog.every((item) => item.schema?.parameters?.arguments?.type === "unknown[]"));
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.AND")?.schema?.returns?.value?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.FILTER")?.schema?.returns?.value?.type, "unknown[][]");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.TEXTJOIN")?.schema?.returns?.value?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.LEN")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.VALUE")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.DATEVALUE")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.DATE")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.NETWORKDAYS")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.NETWORKDAYS.INTL")?.schema?.returns?.value?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.XLOOKUP")?.schema?.returns?.value?.type, "unknown");
const sharedCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "shared");
assert.equal(sharedCatalog.length, 10);
assert.ok(sharedCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "createPopplerRenderer")?.schema?.parameters?.dpi?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "createNativeOfficeRenderer")?.schema?.parameters?.args?.type, "string[]");
assert.equal(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.schema?.parameters?.pixelDiff?.type, "boolean|object");
assert.equal(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.schema?.parameters?.diffImage?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.schema?.parameters?.diffPalette?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.schema?.parameters?.diffAlignment?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "visualQaArtifact")?.schema?.parameters?.pixelRegistration?.type, "boolean|number|object");
const pdfCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "pdf");
assert.equal(pdfCatalog.length, 19);
assert.ok(pdfCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.addText")?.schema?.parameters?.bbox?.type, "number[]");
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.addText")?.schema?.parameters?.headingLevel?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.addPage")?.schema?.parameters?.readingOrder?.type, "string[]|object[]");
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.page.setReadingOrder")?.schema?.parameters?.order?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.addImage")?.schema?.parameters?.decorative?.type, "boolean");
assert.match(HELP_CATALOG.find((item) => item.name === "pdf.addImage")?.schema?.parameters?.alt?.description || "", /required unless decorative/);
assert.equal(HELP_CATALOG.find((item) => item.name === "pdf.addChart")?.schema?.parameters?.alt?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.returns?.blob?.type, "FileBlob");
assert.equal(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.parameters?.tagged?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.parameters?.language?.type, "string");
assert.match(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.parameters?.font?.type || "", /Uint8Array/);
assert.equal(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.parameters?.maxFontBytes?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "PdfFile.exportPdf")?.schema?.parameters?.subsetFont?.type, "boolean");
const documentCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "document");
assert.equal(documentCatalog.length, 34);
assert.ok(documentCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addSection")?.schema?.parameters?.margins?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addListItem")?.schema?.parameters?.pictureBullet?.type, "string|object");
assert.match(HELP_CATALOG.find((item) => item.name === "document.addListItem")?.schema?.parameters?.pictureBullet?.description || "", /Numbering part/);
assert.equal(HELP_CATALOG.find((item) => item.name === "document.addListItem")?.schema?.parameters?.numberingStyleId?.type, "string");
assert.match(HELP_CATALOG.find((item) => item.name === "DocumentModel.create")?.schema?.parameters?.styles?.description || "", /numberingId\/numberingLevel/);
assert.equal(HELP_CATALOG.find((item) => item.name === "DocumentFile.importDocx")?.schema?.returns?.document?.type, "DocumentModel");
const presentationCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "presentation");
assert.equal(presentationCatalog.length, 34);
assert.ok(presentationCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "slide.charts.add")?.schema?.parameters?.series?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.importPptx")?.schema?.returns?.presentation?.type, "Presentation");
assert.equal(HELP_CATALOG.find((item) => item.name === "shape.text.set")?.schema?.parameters?.text?.required, true);
assert.match(HELP_CATALOG.find((item) => item.name === "shape.text.set")?.schema?.parameters?.text?.description || "", /bulletFont.*bulletColor.*bulletSizePercent.*FollowText/);
assert.match(HELP_CATALOG.find((item) => item.name === "shape.text.set")?.schema?.parameters?.text?.description || "", /absolute uri.*slideId.*tooltip.*targetFrame/);
const workbookCatalog = HELP_CATALOG.filter((item) => item.artifactKind === "workbook");
assert.equal(workbookCatalog.length, 138);
assert.ok(workbookCatalog.every((item) => item.schema?.parameters && item.schema?.returns));
assert.equal(HELP_CATALOG.find((item) => item.name === "workbook.trace")?.schema?.parameters?.reference?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "Workbook.create")?.schema?.parameters?.dateSystem?.type, "string");
assert.equal(HELP_CATALOG.find((item) => item.name === "Workbook.create")?.schema?.parameters?.theme?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "range.format")?.schema?.parameters?.fill?.type, "string|object");
assert.equal(HELP_CATALOG.find((item) => item.name === "worksheet.freezePanes.freezeRows")?.schema?.parameters?.rowCount?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "worksheet.freezePanes.freezeColumns")?.schema?.parameters?.columnCount?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "worksheet.mergeCells")?.schema?.parameters?.address?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "range.merge")?.schema?.parameters?.across?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "range.fillDown")?.schema?.returns?.range?.type, "Range");
assert.equal(HELP_CATALOG.find((item) => item.name === "workbook.setDateSystem")?.schema?.parameters?.dateSystem?.type, "string|boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.NETWORKDAYS")?.category, "date-time");
assert.equal(HELP_CATALOG.find((item) => item.name === "fx.WORKDAY.INTL")?.category, "date-time");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.exportXlsx")?.schema?.returns?.blob?.type, "FileBlob");
assert.equal(HELP_CATALOG.find((item) => item.name === "exportXlsxWithOpenXmlWasm")?.schema?.parameters?.allowLossy?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "exportXlsxWithOpenXmlWasm")?.schema?.returns?.blob?.type, "FileBlob");
assert.equal(HELP_CATALOG.find((item) => item.name === "exportDocxWithOpenXmlWasm")?.schema?.parameters?.allowLossy?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "exportDocxWithOpenXmlWasm")?.schema?.returns?.blob?.type, "FileBlob");
assert.equal(HELP_CATALOG.find((item) => item.name === "importDocxWithOpenXmlWasm")?.schema?.returns?.document?.type, "DocumentModel");
assert.equal(HELP_CATALOG.find((item) => item.name === "importXlsxWithOpenXmlWasm")?.schema?.parameters?.limits?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "openXmlWasmStatus")?.schema?.returns?.status?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "invokeOpenXmlWasm")?.schema?.parameters?.request?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.inspectXlsx")?.schema?.parameters?.maxTotalBytes?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.patchXlsx")?.schema?.parameters?.validateResult?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.patchXlsx")?.schema?.parameters?.syncSourceReferences?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.patchXlsx")?.schema?.parameters?.recipe?.type, "string|object");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.importDelimited")?.schema?.parameters?.maxRows?.type, "number");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.exportCsv")?.schema?.parameters?.formulas?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "SpreadsheetFile.inspectDelimited")?.schema?.returns?.inspection?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.type, "object[]");
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /lazy IF\/IFERROR/);
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /LEN\/LEFT\/RIGHT\/MID/);
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /DATE\/YEAR\/MONTH\/DAY/);
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /EDATE\/EOMONTH\/DAYS\/WEEKDAY/);
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /TIME\/HOUR\/MINUTE\/SECOND/);
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /NETWORKDAYS\/WORKDAY\/NETWORKDAYS.INTL\/WORKDAY.INTL/);
assert.match(HELP_CATALOG.find((item) => item.name === "sheet.pivotTables.add")?.schema?.parameters?.calculatedFields?.description || "", /one optional scalar holiday/);
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.patches?.required, true);
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.syncContentTypes?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.validateResult?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.syncSourceReferences?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.recipe?.type, "string|object");
assert.match(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.sourceReference?.description || "", /explicit pixel position/);
assert.match(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.validateResult?.description || "", /notes\/comments semantics/);
assert.equal(HELP_CATALOG.find((item) => item.name === "PresentationFile.patchPptx")?.schema?.parameters?.relationship?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "DocumentFile.patchDocx")?.schema?.parameters?.validateResult?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "DocumentFile.patchDocx")?.schema?.parameters?.syncSourceReferences?.type, "boolean");
assert.equal(HELP_CATALOG.find((item) => item.name === "DocumentFile.patchDocx")?.schema?.parameters?.recipe?.type, "string|object");

const workbook = Workbook.create();
const presentation = Presentation.create();
const document = DocumentModel.create({ paragraphs: ["Doc"] });
const pdf = PdfArtifact.create({ text: "PDF" });

assert.match(workbook.help("sheet.charts.add").ndjson, /worksheet chart/);
assert.match(workbook.help("workbook.formulaGraph").ndjson, /dependency graph/);
assert.match(workbook.help("fx.AVERAGE").ndjson, /Average numeric values/);
assert.match(workbook.help("fx.XLOOKUP").ndjson, /lookup/);
assert.match(workbook.help("fx.TEXTJOIN").ndjson, /delimiter/);
assert.match(workbook.help("fx.SUMPRODUCT").ndjson, /products/);
assert.match(workbook.help("fx.HLOOKUP").ndjson, /first row/);
assert.match(workbook.help("fx.IFERROR").ndjson, /formula error/);
assert.match(workbook.help("fx.AVERAGEIFS").ndjson, /criteria ranges/);
assert.match(presentation.help("slide.compose").ndjson, /compose tree/);
assert.match(presentation.help("slide.addNotes").ndjson, /speaker notes/);
assert.match(presentation.help("slide.connectors.add").ndjson, /connector line/);
assert.match(presentation.help("presentation.theme").ndjson, /theme colors/);
assert.equal(HELP_CATALOG.find((item) => item.name === "presentation.theme")?.schema?.parameters?.textStyles?.type, "object");
assert.equal(HELP_CATALOG.find((item) => item.name === "presentation.theme")?.schema?.parameters?.colorMap?.type, "object");
assert.match(HELP_CATALOG.find((item) => item.name === "presentation.theme")?.summary || "", /Slide Master inheritance/);
assert.match(presentation.help("presentation.layouts.add").ndjson, /slide layout/);
assert.match(document.help("document.addField").ndjson, /fldSimple/);
assert.match(document.help("document.addBookmark").ndjson, /bookmark range/);
assert.match(document.help("document.addBibliographySource").ndjson, /bibliography source/);
assert.match(document.help("document.applyDesignPreset").ndjson, /design preset/);
assert.match(document.help("document.layoutJson").ndjson, /layout JSON/);
assert.match(document.help("document.resolve").ndjson, /stable document/);
assert.match(document.help("DocumentFile.importDocx").ndjson, /relationship-driven DOCX semantics/);
assert.match(pdf.help("extractTables").ndjson, /table values/);
assert.match(pdf.help("createPdfjsParser").ndjson, /positioned text/);
assert.match(helpArtifact("*", "renderArtifact").ndjson, /FileBlob metadata/);
assert.match(helpArtifact("shared", "visualQaArtifact").ndjson, /baseline render/);
assert.match(helpArtifact("shared", "createPlaywrightRenderer").ndjson, /Playwright renderer adapter/);
assert.match(helpArtifact("shared", "createSharpRenderer").ndjson, /sharp renderer adapter/);
assert.match(helpArtifact("shared", "createPopplerRenderer").ndjson, /Poppler CLI renderer adapter/);
assert.match(helpArtifact("shared", "createLibreOfficeRenderer").ndjson, /LibreOffice CLI renderer adapter/);
assert.match(helpArtifact("presentation", "PresentationFile.inspectPptx").ndjson, /PPTX package/);
assert.match(helpArtifact("pdf", "PdfFile.inspectPdf").ndjson, /PDF bytes/);
assert.match(helpArtifact("shared", "createNativeOfficeRenderer").ndjson, /native Office renderer adapter/);
assert.match(helpArtifact("shared", "renderFileWithNativeOffice").ndjson, /native Office bridge command/);
assert.match(helpArtifact("shared", "pixelDiff").ndjson, /visualQaArtifact/);
assert.match(helpArtifact("workbook", "include\/fields").ndjson, /workbook.inspect/);
assert.match(helpArtifact("workbook", "colorScale").ndjson, /range\.conditionalFormats\.add/);
assert.match(helpArtifact("document", "maxPatchBytes").ndjson, /DocumentFile\.patchDocx/);
assert.match(helpArtifact(workbook, "fx.PMT").ndjson, /financial/);
assert.equal(helpArtifact("presentation", "sheet.charts.add").ndjson, "");
const apiDocs = await fs.readFile(new URL("../docs/api.md", import.meta.url), "utf8");
assert.match(apiDocs, /### shared details/);
assert.match(apiDocs, /#### `renderArtifact`/);
assert.match(apiDocs, /await renderArtifact\(document/);
assert.match(apiDocs, /#### `workbook.inspect`/);
assert.match(apiDocs, /include\/fields/);
assert.match(apiDocs, /\*\*Schema parameters:\*\*/);
assert.match(apiDocs, /`kind` \(string\)/);
assert.match(apiDocs, /`blob` \(FileBlob\)/);
assert.match(apiDocs, /DocumentFile\.patchDocx/);
assert.match(apiDocs, /#### `fx\.FILTER`/);
assert.match(apiDocs, /Spilled two-dimensional formula result/);
assert.match(apiDocs, /#### `createPopplerRenderer`/);
assert.match(apiDocs, /`dpi` \(number\)/);
assert.match(apiDocs, /#### `visualQaArtifact`/);
assert.match(apiDocs, /#### `pdf\.addPage`/);
assert.match(apiDocs, /#### `pdf\.addTable`/);
assert.match(apiDocs, /#### `document\.resolve`/);
assert.match(apiDocs, /#### `DocumentFile\.importDocx`/);
assert.match(apiDocs, /#### `presentation\.slides\.add`/);
assert.match(apiDocs, /#### `PresentationFile\.importPptx`/);
assert.match(apiDocs, /#### `workbook\.worksheets\.add`/);
assert.match(apiDocs, /#### `workbook\.recalculate`/);
assert.match(apiDocs, /#### `fx\.TAKE`/);
assert.match(apiDocs, /#### `SpreadsheetFile\.inspectXlsx`/);
assert.match(apiDocs, /#### `PresentationFile\.patchPptx`/);

console.log("help smoke ok");
