// This is deliberately small, explicit .NET JavaScript interop glue for the
// one OpenChestnut request/response boundary. The .NET 8 JSExport generator
// derives its wrapper name from String.GetHashCode(), which is randomized per
// compiler process and prevents reproducible WASM output. Keep this ABI in
// sync with the generated byte[] -> byte[] bridge; the stable hash below is
// derived from the return and parameter type names character by character.

namespace System.Runtime.InteropServices.JavaScript
{

[global::System.Runtime.Versioning.SupportedOSPlatform("browser")]
unsafe static class OpenChestnutJavaScriptInterop
{
    private const int InvokeTypesHash = 2080084849;

    [global::System.ThreadStatic]
    private static bool initialized;

    [global::System.Diagnostics.CodeAnalysis.DynamicDependency(
        "__Wrapper_Invoke_2080084849",
        "OpenChestnutExports",
        "OpenChestnut.Runtime")]
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Register()
    {
        if (initialized || global::System.Runtime.InteropServices.RuntimeInformation.OSArchitecture != global::System.Runtime.InteropServices.Architecture.Wasm)
            return;

        initialized = true;
        JSFunctionBinding.BindManagedFunction(
            "[OpenChestnut.Runtime]OpenChestnutExports:Invoke",
            InvokeTypesHash,
            [JSMarshalerType.Array(JSMarshalerType.Byte), JSMarshalerType.Array(JSMarshalerType.Byte)]);
    }
}

}

public unsafe partial class OpenChestnutExports
{
    [global::System.Diagnostics.DebuggerNonUserCode]
    internal static void __Wrapper_Invoke_2080084849(global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument* arguments)
    {
        ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument exception = ref arguments[0];
        ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument result = ref arguments[1];
        ref global::System.Runtime.InteropServices.JavaScript.JSMarshalerArgument request = ref arguments[2];

        try
        {
            request.ToManaged(out byte[] requestBytes);
            result.ToJS(Invoke(requestBytes));
        }
        catch (global::System.Exception error)
        {
            exception.ToJS(error);
        }
    }
}
